# Generated by Django 5.2.18 on 2026-10-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0011_unit_cost_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actor',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
