# Generated by Django 5.2.18 on 2026-10-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0013_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='erp_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='is_stocked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='revision',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='standard_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
